<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LPCAIQ1099" failures="2" tests="2" name="FormPageValidationTests" time="66.816" errors="0" timestamp="2024-08-17T16:34:20 EET">
  <testcase classname="Tests.FormPageValidationTests" name="FormPositiveScenario" time="11.453">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at Tests.FormPageValidationTests.FormPositiveScenario(FormPageValidationTests.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- FormPositiveScenario -->
  <testcase classname="Tests.FormPageValidationTests" name="FormPositiveScenario" time="24.133">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at Tests.FormPageValidationTests.FormPositiveScenario(FormPageValidationTests.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- FormPositiveScenario -->
</testsuite> <!-- FormPageValidationTests -->
